export const validCatalogEligibility = {
  variant_id: "variant-1",
  product_id: "product-1",
  brand_id: null,
  sku: "SKU-SERVER",
  variant_slug: "variant-1",
  variant_name: "Variant",
  localized_name: "Variant",
  product_slug: "product-1",
  product_name: "Product",
  localized_product_name: "Product",
  brand_slug: null,
  brand_name: null,
  image_url: null,
  price: 125000,
  stock: 1,
  price_mode: "fixed",
  has_fresh_stock: true,
  has_supported_media: true,
  catalog_approved_validated: true,
  hidden_brand_sku: false,
  reason_codes: [],
  storefront: true,
  recommendation: true,
  visual_match: true,
  cart: true,
  payment: true,
} as const;
